name:                 noname
version:              0.3
visibility:           public
id:                   noname-0.3-inplace
key:                  noname-0.3-inplace
license:              BSD-3-Clause
copyright:            2023 Technical University of Denmark
maintainer:           lpkf@dtu.dk
author:               Laouen Fernet
synopsis:             Formal verification of privacy in security protocols.
description:
    This tool is an implementation of a decision procedure for \(\alpha,
    \beta)\)-privacy, for a bounded number of transitions. Write the specification
    of a security protocol and verify whether the privacy goals are achieved. In
    case there is a privacy violation, the tool shows a reachable state of the
    protocol in which the intruder has learned more information than what is
    allowed.

category:             Formal Methods
abi:                  inplace
exposed:              True
exposed-modules:
    Noname Noname.Analysis Noname.ComposeChecks Noname.Evaluation
    Noname.LazyIntruder Noname.NonDetState Noname.Parser Noname.Pretty
    Noname.Reachability Noname.State Noname.Unification
    Noname.Verification

import-dirs:
    /Users/elisabetbirgisdottir/Documents/GitHub/noname_gui/noname/dist-newstyle/build/aarch64-osx/ghc-9.6.7/noname-0.3/build

library-dirs:
    /Users/elisabetbirgisdottir/Documents/GitHub/noname_gui/noname/dist-newstyle/build/aarch64-osx/ghc-9.6.7/noname-0.3/build

library-dirs-static:
    /Users/elisabetbirgisdottir/Documents/GitHub/noname_gui/noname/dist-newstyle/build/aarch64-osx/ghc-9.6.7/noname-0.3/build

dynamic-library-dirs:
    /Users/elisabetbirgisdottir/Documents/GitHub/noname_gui/noname/dist-newstyle/build/aarch64-osx/ghc-9.6.7/noname-0.3/build

data-dir:
    /Users/elisabetbirgisdottir/Documents/GitHub/noname_gui/noname/.

hs-libraries:         HSnoname-0.3-inplace
depends:
    base-4.18.3.0 containers-0.6.7 mgprsc-9.7.0-8efd96d3
    prsr-cmbntrs-1.3.1-5403f31d sbv-10.12-aa233811 txt-2.1.3-8183658d
    transformers-0.6.1.0 nlft-0.2.25.1-a61adf59

haddock-interfaces:
    /Users/elisabetbirgisdottir/Documents/GitHub/noname_gui/noname/dist-newstyle/build/aarch64-osx/ghc-9.6.7/noname-0.3/doc/html/noname/noname.haddock

haddock-html:
    /Users/elisabetbirgisdottir/Documents/GitHub/noname_gui/noname/dist-newstyle/build/aarch64-osx/ghc-9.6.7/noname-0.3/doc/html/noname
